### PR TITLE
Migrated to Google's latest batch-style RPC API

### PR DESCRIPTION
**Pull request by vkedwardli**
Credits: https://kovatch.medium.com/deciphering-google-batchexecute-74991e4e446c

### CODE REVIEW

**Comment by vkedwardli** [comment]
https://github.com/vitalets/google-translate-api/blame/master/README.md#L19-L20

These won't be applicable anymore

**Comment by ArtanisTheOne** [comment]
Awesome!

**Comment by Mrshulan** [comment]
Does not seem to support batch translation?

**Comment by vkedwardli** [comment]
@Mrshulan what do you mean by batch translation? How did you call this feature originally?

**Comment by ArtanisTheOne** [comment]
There is a small .forEach error which occurs, not sure if there is a pattern but it doesnt seem to affect functionality

**Comment by vkedwardli** [comment]
@ArtanisTheOne Could you provide a test case for the `.forEach` error? thanks

**Comment by ArtanisTheOne** [comment]
This is the error:

`Unhandled Rejection
Caused By:
TypeError: Cannot read property 'forEach' of null
Url: https://translate.google.com/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&f.sid=6985033324950636370&bl=boq_translate-webserver_20210105.10_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=2421&rt=c
    at /app/node_modules/google-translate-api/index.js:94:34
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

The file used to interact with the branch: https://github.com/ZyC0R3/RitaBot/blob/master/src/core/translate.js

And I havent been able to recreate the error within a controlled environment, it just "happens."

**Comment by vkedwardli** [comment]
@ArtanisTheOne thanks for the error log.
The error is `json[1][0][0][5]` being `null`, which means there is no translated text being returned.

E.g. If we just submit an hyperlink to the service, `json[1][0][0][5]` will be `undefined`. (Fixed in https://github.com/vitalets/google-translate-api/pull/61/commits/12808667670ee0c08b7354edb4fa545785582679)

So I guess there are still other cases which Google won't translate the input at all

**Comment by ArtanisTheOne** [comment]
Thanks, I had forgotten to get a fresh install of the modules so it was using your previous version. Thank you for the awesome work by the way! @vkedwardli

**Review by ArtanisTheOne — APPROVED** [review]

**Comment by ZyC0R3** [comment]
@vkedwardli Are you able to join our discord server, would love to have you help with the RITA project.

**Comment by vkedwardli** [comment]
@ZyC0R3 ping me at edw#0809

**Comment by tintaneltres** [comment]
Is this working yet? Quite new to all this but i would love to use it if it is. Thank you. :)

**Comment by vitalets** [comment]
@vkedwardli many-many thanks for this pr!!
Published as v5.0.0.
Let me know if something does not work.

**Pull request merged**
