### PR TITLE
Update index.js to allow adding got opts

### PR DESCRIPTION
**Pull request by noname001**

### CODE REVIEW

**Comment by vitalets** [comment]
@noname001 Could you show the case when this is needed?

**Comment by noname001** [comment]
@vitalets Google Translate has request limits to avoid them you need to use a proxy:
`const translate = require('@vitalets/google-translate-api'),
tunnel = require('tunnel');
translate('Ik spreek Engels', {to: 'en'}, {agent: tunnel.httpsOverHttp({
    proxy: { 
      host: 'whateverhost',
      proxyAuth: "user:pass",
      port: '8080',
      headers: {
        'User-Agent': 'Node'
      }
    }
  })})`

**Comment by vitalets** [comment]
Yes, that's useful!
Could you add tests and update readme to let other people know about `gotopts` parameter.

**Comment by noname001** [comment]
Readme - well done. What tests should check? Even if tests are necessary, I do not have enough time to write them.

**Comment by vitalets** [comment]
> What tests should check?

I think single test for a particular `got` option is enough. For example, we can check that [hooks.afterResponse](https://github.com/sindresorhus/got#hooksafterresponse) is called.

**Comment by ZyC0R3** [comment]
this seems like it would resolve the issuie with 429 and 503 ( #9) error and #30 

Any update on if this will be merged and if the porxy will be added in.

**Comment by vitalets** [comment]
> this seems like it would resolve the issuie with roor 429 and 503 ( #9 #3 ) error and #30
> 
> Any update on if this will be merged and if the porxy will be added in.

Released as 2.9.0.

**Pull request merged**
