### PR TITLE
Update index.js to allow for language additions from outside of the API

### PR DESCRIPTION
**Pull request by coltongit**
Updates index.js to allow for language additions from outside of the API (carryover from unmaintained upstream PR https://github.com/matheuss/google-translate-api/pull/31).

### CODE REVIEW

**Comment by vitalets** [comment]
Good feature! Could you add a documentation to readme how to use it?

**Comment by coltongit** [comment]
> Good feature! Could you add to readme a usage example?

Sure. I can reference what the original upstream PR had for instructions and mirror those in the readme if you like.

**Comment by vitalets** [comment]
This is cool! 👍 
Please 
* rebase to master to resolve conflicts in readme
* add test for that feature

**Comment by coltongit** [comment]
The repo's been rebased around the current master. The test for this will be worked on shortly.

**Comment by coltongit** [comment]
I've coded a WIP test for this particular feature. Testing would be very much appreciated.

**Comment by vitalets** [comment]
Thank you! 👍

**Pull request merged**
